/**
 * Generates drizzle/seed/0001_forms.sql from the canonical form definitions.
 * Idempotent: INSERT OR IGNORE on forms/form_versions/settings, then point
 * forms.current_version_id at version 1 only when it is still NULL.
 *
 * Later edits happen through Admin (new versions) — never by re-seeding.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { canonicalForms } from "../src/forms/canonical";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const now = Date.now();

// Deterministic ids so re-running never creates a second copy.
const FORM_IDS: Record<string, string> = {
  community: "form_community",
  generic_csc: "form_generic_csc",
  high_ticket: "form_high_ticket",
};

const lines: string[] = ["-- Generated by scripts/build-seed-sql.ts. Do not edit by hand.", ""];

for (const [slug, def] of Object.entries(canonicalForms)) {
  const formId = FORM_IDS[slug];
  const versionId = `${formId}_v1`;
  lines.push(
    `INSERT OR IGNORE INTO forms (id, slug, title, status, access, current_version_id, created_at, updated_at) VALUES (${q(formId)}, ${q(slug)}, ${q(def.title)}, 'enabled', 'public', NULL, ${now}, ${now});`,
    `INSERT OR IGNORE INTO form_versions (id, form_id, version, status, definition_json, change_note, created_by, created_at, published_at) VALUES (${q(versionId)}, ${q(formId)}, 1, 'published', ${q(JSON.stringify(def))}, 'Initial canonical version', 'seed', ${now}, ${now});`,
    `UPDATE forms SET current_version_id = ${q(versionId)} WHERE id = ${q(formId)} AND current_version_id IS NULL;`,
    "",
  );
}

const defaultSettings: Record<string, unknown> = {
  whatsapp_invite_url: "",
  csc_info_url: "",
  privacy_url: "",
  notification_recipients: [],
  notion_db_generic_csc: "",
  notion_db_high_ticket: "",
  notion_db_community: "",
  duplicate_window_days: 30,
  turnstile_enabled: false,
  turnstile_site_key: "",
  admin_base_url: "",
};
for (const [key, value] of Object.entries(defaultSettings)) {
  lines.push(`INSERT OR IGNORE INTO settings (key, value_json, updated_at, updated_by) VALUES (${q(key)}, ${q(JSON.stringify(value))}, ${now}, 'seed');`);
}

mkdirSync("drizzle/seed", { recursive: true });
writeFileSync("drizzle/seed/0001_forms.sql", lines.join("\n") + "\n");
console.log("Wrote drizzle/seed/0001_forms.sql");
